from __future__ import annotations

from datetime import timedelta

from .models import AuditEvent, Device, DeviceRun, Job, Pool, Session, StepResult, iso, utcnow
from .store import Store


def seed(store: Store) -> None:
    pools = [
        Pool("pool-smoke", "Smoke", "Fast confidence checks before a merge.", "#c45c26"),
        Pool("pool-regression", "Regression", "Broader OS and form-factor coverage.", "#3d6b54"),
        Pool("pool-manual", "Manual QA", "Reserved desks for reproducing bugs by hand.", "#2b4c7e"),
    ]
    for pool in pools:
        store.add_pool(pool)

    devices = [
        Device(
            id="px8p",
            serial="1A2B3C4D5E6F",
            name="Pixel 8 Pro",
            manufacturer="Google",
            model="husky",
            form_factor="phone",
            os="Android",
            os_version="15",
            api_level=35,
            abi="arm64-v8a",
            status="online",
            battery=91,
            charging=True,
            temperature_c=32.4,
            storage_free_gb=48.2,
            pool_id="pool-smoke",
            tags=["flagship", "high-dpi"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
            screen_w=1344,
            screen_h=2992,
        ),
        Device(
            id="px7a",
            serial="G7A-8821-CC",
            name="Pixel 7a",
            manufacturer="Google",
            model="lynx",
            form_factor="phone",
            os="Android",
            os_version="14",
            api_level=34,
            abi="arm64-v8a",
            status="online",
            battery=64,
            charging=False,
            temperature_c=34.1,
            storage_free_gb=22.0,
            pool_id="pool-smoke",
            tags=["midrange"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
        ),
        Device(
            id="s24",
            serial="R5CT90ABCDE",
            name="Galaxy S24",
            manufacturer="Samsung",
            model="e1q",
            form_factor="phone",
            os="Android",
            os_version="14",
            api_level=34,
            abi="arm64-v8a",
            status="busy",
            battery=71,
            charging=True,
            temperature_c=36.8,
            storage_free_gb=91.4,
            pool_id="pool-smoke",
            tags=["flagship", "one-ui"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
        ),
        Device(
            id="px6a",
            serial="1B0C9D8E7F6A",
            name="Pixel 6a",
            manufacturer="Google",
            model="bluejay",
            form_factor="phone",
            os="Android",
            os_version="13",
            api_level=33,
            abi="arm64-v8a",
            status="online",
            battery=48,
            charging=False,
            temperature_c=33.0,
            storage_free_gb=11.6,
            pool_id="pool-regression",
            tags=["older-api"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
        ),
        Device(
            id="a54",
            serial="R58M80XYZ12",
            name="Galaxy A54",
            manufacturer="Samsung",
            model="a54x",
            form_factor="phone",
            os="Android",
            os_version="14",
            api_level=34,
            abi="arm64-v8a",
            status="online",
            battery=12,
            charging=False,
            temperature_c=31.2,
            storage_free_gb=6.1,
            pool_id="pool-regression",
            tags=["budget"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
            notes="Low battery — plug in before the next automated batch.",
        ),
        Device(
            id="gpower",
            serial="ZY22B2T3P4",
            name="moto g power",
            manufacturer="Motorola",
            model="tundra",
            form_factor="phone",
            os="Android",
            os_version="12",
            api_level=32,
            abi="arm64-v8a",
            status="online",
            battery=83,
            charging=True,
            temperature_c=30.5,
            storage_free_gb=18.9,
            pool_id="pool-regression",
            tags=["older-api", "low-end"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
            screen_w=1080,
            screen_h=2400,
        ),
        Device(
            id="op12",
            serial="a4b8c1d2e3",
            name="OnePlus 12",
            manufacturer="OnePlus",
            model="waffle",
            form_factor="phone",
            os="Android",
            os_version="15",
            api_level=35,
            abi="arm64-v8a",
            status="online",
            battery=77,
            charging=False,
            temperature_c=41.6,
            storage_free_gb=128.0,
            pool_id="pool-regression",
            tags=["flagship", "oxygenos"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
            notes="Warm from a previous suite. Scheduler will wait to cool.",
        ),
        Device(
            id="pxtab",
            serial="TAB-441-OK",
            name="Pixel Tablet",
            manufacturer="Google",
            model="tangorpro",
            form_factor="tablet",
            os="Android",
            os_version="14",
            api_level=34,
            abi="arm64-v8a",
            status="online",
            battery=100,
            charging=True,
            temperature_c=29.8,
            storage_free_gb=210.2,
            pool_id="pool-regression",
            tags=["tablet"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
            screen_w=1600,
            screen_h=2560,
        ),
        Device(
            id="tabs9",
            serial="R52X80TABLET",
            name="Galaxy Tab S9",
            manufacturer="Samsung",
            model="gts9",
            form_factor="tablet",
            os="Android",
            os_version="14",
            api_level=34,
            abi="arm64-v8a",
            status="online",
            battery=55,
            charging=False,
            temperature_c=31.4,
            storage_free_gb=1.4,
            pool_id="pool-regression",
            tags=["tablet", "one-ui"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
            screen_w=1600,
            screen_h=2560,
        ),
        Device(
            id="nothi",
            serial="P2A-9910",
            name="Nothing Phone (2)",
            manufacturer="Nothing",
            model="Pong",
            form_factor="phone",
            os="Android",
            os_version="14",
            api_level=34,
            abi="arm64-v8a",
            status="offline",
            battery=40,
            charging=False,
            temperature_c=27.0,
            storage_free_gb=33.3,
            pool_id="pool-regression",
            tags=["glyph"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
        ),
        Device(
            id="px9",
            serial="9F8E7D6C5B",
            name="Pixel 9",
            manufacturer="Google",
            model="tokay",
            form_factor="phone",
            os="Android",
            os_version="15",
            api_level=35,
            abi="arm64-v8a",
            status="reserved",
            battery=88,
            charging=True,
            temperature_c=31.0,
            storage_free_gb=72.5,
            pool_id="pool-manual",
            tags=["flagship"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
            reserved_by="amina",
            reserved_until=iso(utcnow() + timedelta(minutes=45)),
        ),
        Device(
            id="flip5",
            serial="RF8X90FLIP",
            name="Galaxy Z Flip5",
            manufacturer="Samsung",
            model="b5q",
            form_factor="foldable",
            os="Android",
            os_version="14",
            api_level=34,
            abi="arm64-v8a",
            status="online",
            battery=69,
            charging=False,
            temperature_c=33.7,
            storage_free_gb=54.0,
            pool_id="pool-manual",
            tags=["foldable"],
            source="simulator",
            automatable=True,
            last_seen=iso(),
            screen_w=1080,
            screen_h=2640,
        ),
        Device(
            id="iph15",
            serial="F2LXXXXIPHONE",
            name="iPhone 15",
            manufacturer="Apple",
            model="iPhone15,4",
            form_factor="phone",
            os="iOS",
            os_version="18.2",
            api_level=18,
            abi="arm64",
            status="online",
            battery=81,
            charging=True,
            temperature_c=30.2,
            storage_free_gb=40.0,
            pool_id="pool-manual",
            tags=["ios", "manual-only"],
            source="manual",
            automatable=False,
            last_seen=iso(),
            notes="Manual sessions only. Automated jobs require a Mac + XCTest runner.",
            screen_w=1179,
            screen_h=2556,
        ),
        Device(
            id="ipad",
            serial="IPAD-MANUAL-01",
            name="iPad Air",
            manufacturer="Apple",
            model="iPad14,2",
            form_factor="tablet",
            os="iOS",
            os_version="18.1",
            api_level=18,
            abi="arm64",
            status="maintenance",
            battery=20,
            charging=True,
            temperature_c=28.0,
            storage_free_gb=12.2,
            pool_id="pool-manual",
            tags=["ios", "manual-only"],
            source="manual",
            automatable=False,
            last_seen=iso(),
            notes="Waiting on a cable replacement.",
            screen_w=1640,
            screen_h=2360,
        ),
    ]
    for device in devices:
        store.add_device(device)

    store.add_job(
        Job(
            id="job-live01",
            name="Merge smoke — checkout",
            suite="smoke",
            app_label="com.example.shop",
            pool_id="pool-smoke",
            device_ids=["s24"],
            status="running",
            created_at=iso(),
            created_by="ci",
            started_at=iso(),
            notes="Triggered from the demo rack.",
            runs=[
                DeviceRun(
                    device_id="s24",
                    status="running",
                    started_at=iso(),
                    steps=[
                        StepResult("verify_device_health", "passed", 640),
                        StepResult("install_app_under_test", "passed", 2100),
                        StepResult("cold_launch", "running", 400),
                    ],
                )
            ],
        )
    )
    store.add_session(
        Session(
            id="ses-manual1",
            device_id="px9",
            operator="amina",
            purpose="Reproduce checkout crash on API 35",
            started_at=iso(),
        )
    )
    store.add_audit(
        AuditEvent(
            id="aud-seed-1",
            at=iso(),
            actor="lab",
            action="seed",
            target="bench",
            detail="Loaded demo rack so the lab is usable without USB phones.",
        )
    )
    store.add_audit(
        AuditEvent(
            id="aud-seed-2",
            at=iso(),
            actor="ci",
            action="enqueue_job",
            target="job-live01",
            detail="smoke on 1 device(s) for com.example.shop",
        )
    )
